### ISSUE TITLE
获取redis监控数据是，zone为空

### ISSUE THREAD

**Issue by TinyQAQ** [tencentyun/tencentcloud-exporter#22]
qce_redis_bigvaluemin_sum{instance_name="ak-php-saas-21",instanceid="crs-rv962yek",zone=""} 8.416

instance_name 正常
zone 为空

**Comment by TinyQAQ** [comment]
配置文件概览

```
products:
  - namespace: QCE/REDIS    # 指标详情: https://cloud.tencent.com/document/product/248/45111
    all_metrics: true
    all_instances: true
    #only_include_metrics: []
    #only_include_instances: [crs-xxxxxxxx]
    extra_labels: [InstanceName,Zone]
    #statistics_types: [last]
    #period_seconds: 60
    #metric_name_type: 2
```
