### ISSUE TITLE
无法获取 cdn 数据

### ISSUE THREAD

**Issue by LeoQuote** [tencentyun/tencentcloud-exporter#41]
```
  credential:
    region: ap-beijing

  products:
  - namespace: QCE/CDN
    all_metrics: true
    all_instances: true
```

配置后无法抓取, metric 页面上显示抓取成功, 但是没有对应的指标, 一个也没有
