### ISSUE TITLE
升级到最新版 V2.19.0 后, cdn 指标抓取失败 msg="this instance may not have metric data"

### ISSUE THREAD

**Issue by LeoQuote** [tencentyun/tencentcloud-exporter#93]
```
ts=2022-12-07T14:30:53.855Z caller=repository.go:200 level=debug msg="this instance may not have metric data" metric=Bandwidth dimension="map[domain:xxx projectId:xxx]"
```

配置文件 
```
credential:
  region: ap-guangzhou
products:
- namespace: QCE/CDN
  only_include_metrics:
    - RequestsHitRate
    - FluxHitRate
    - HttpStatus4xxRate
    - HttpStatus403Rate
    - HttpStatus5xxRate
    - Bandwidth
    - BackOriginBandwidth
    - BackOriginHttp4xx
    - BackOriginHttp5xx
    - BackOriginHttp403
    - BackOriginHttp404
    - BackOriginRequests
  custom_query_dimensions:
  - projectId: xxx
    domain: xxx
  - projectId: xxx
    domain: xxx
  - projectId: xxx
    domain: xxx
  - projectId: xxx
    domain: xxx
rate_limit: 10
```
